### ISSUE TITLE
pinned numpy

### ISSUE THREAD

**Issue by haesleinhuepf** [kevinyamauchi/morphometrics#25]
Hi @kevinyamauchi ,

just a quick question, I'm receiving some package version incompatibility warning messages, caused by [this line](https://github.com/kevinyamauchi/morphometrics/blob/main/setup.cfg#L39). I was just wondering why numpy is pinned in `morphometrics`. Is there any particular known issue?

Thanks!

Best,
Robert

**Comment by kevinyamauchi** [comment]
Hey @haesleinhuepf ! The `numpy < 1.22` is due to [numba’s numpy requirement](https://numba.readthedocs.io/en/stable/user/installing.html). Out of curiosity, which library are you using that requires `numpy >= 1.22`?

**Comment by haesleinhuepf** [comment]
Ok, cool. [Just a link for completeness](https://github.com/conda-forge/numba-feedstock/blob/main/recipe/meta.yaml#L64).

> Out of curiosity, which library are you using that requires numpy >= 1.22?

I'm not sure (I saw the warning during installation using pip on another PC which I don't have access to).

I'm now wondering if it would make sense to pin numpy < 1.22.0 in [devbio-napari](https://github.com/haesleinhuepf/devbio-napari/blob/master/setup.cfg#L35). You know, that's the package we would like to make work on as many computers as possible, and I was thinking of adding morphometrics to it. How's you experience with morphometrics, does it always install well or are there any known issues on rare operating systems?

**Comment by haesleinhuepf** [comment]
Ok, I found it:

```
pyshtools 4.10 requires numpy>=1.22.3, but you have numpy 1.21.5 which is incompatible.
```

[pyshtools](https://github.com/SHTOOLS/SHTOOLS/blob/master/setup.py#L73) is used in [napari-stress](https://github.com/BiAPoL/napari-stress) ...

I'll create an issue there. Thanks for your feedback @kevinyamauchi !

**Comment by kevinyamauchi** [comment]
> How's you experience with morphometrics, does it always install well or are there any known issues on rare operating systems?

My experience so far has been that the installation fairly straightforward. The one wrinkle is potential issues with openCL (used for an awesome library you may have heard of called `pyclesperanto`), but I imagine the dev-bio package already has that sorted ;)
